product_management/config/routes.rb
Rails.application.routes.draw do

  # devise_for :employees
  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords:'admins/passwords', confirmations:'admins/confirmations', unlocks:'admins/unlocks'}

  scope "(:locale)" do
    root to: "admin/admins#index"
    namespace :admin, path: "admin/:business_client_key" do
      root to: "admins#index"
      resources :admins, param: :uid
      resources :product_groups, param: :uid do
        resources :products, param: :uid do
          resources :product_add_ons, param: :uid
        end
      end
      resources :shops, param: :uid do
        resources :shop_operation_times, param: :uid
        resources :time_interval_products, param: :uid
        resources :employees, param: :uid
        resources :statuses, param: :uid
        resources :shop_products, param: :uid do
          resources :shop_product_add_ons, param: :uid
        end
      end

      resources :order_product_add_ons, param: :uid
      resources :order_products, param: :uid
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end
      resources :add_ons, param: :uid
      resources :business_clients, param: :uid
    end

    namespace :customer, path: "customer/:business_client_key" do
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end

    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

product_management/app/models/product_group.rb
# == Schema Information
#
# Table name: product_groups
#
#  id                 :integer          not null, primary key
#  uid                :text
#  business_client_id :integer
#  name               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class ProductGroup < ApplicationRecord
  belongs_to :business_client

  has_many :products

  validates :name, presence: true
  validates :business_client, presence: true
  
end

product_management/app/models/shop_product.rb
# == Schema Information
#
# Table name: shop_products
#
#  id         :integer          not null, primary key
#  uid        :text
#  price      :decimal(, )
#  quantity   :integer
#  shop_id    :integer
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShopProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product

  has_many :order_products
  has_many :shop_product_add_ons
  has_many :time_interval_products

  validates :product, presence: true
  validates :shop, uniqueness: { scope: :product_id }

  def get_product_price(product_id)
    product = @main_business_client.products.find(product_id)
    return product.price
  end

end

product_management/app/controllers/admin/shop_products_controller.rb
class Admin::ShopProductsController < Admin::AppController
  before_action :set_shop
  before_action :set_shop_product, only: [:show, :create, :edit, :update, :destroy]

  # GET /shop_products
  # GET /shop_products.json
  def index
    @shop_products = @shop.shop_products
  end

  # GET /shop_products/1
  # GET /shop_products/1.json
  def show
  end

  # GET /shop_products/new
  def new
    @products = @main_business_client.products.where.not(id: @shop.shop_products.map(&:product).flatten.map(&:id))
  end

  # GET /shop_products/1/edit
  def edit
  end

  # POST /shop_products
  # POST /shop_products.json
  def create
    has_error = false
    error = ""
    if !params[:product_ids].nil?
      begin
        ActiveRecord::Base.transaction do
          params[:product_ids].each do |product_id|
            product_id = product_id.to_i
            product = @main_business_client.products.find(product_id)
            price = product.price
            ShopProduct.create!(shop_id: @shop.id, product_id: product_id, price: price)
          end
        end
      rescue ActiveRecord::RecordInvalid => e
        has_error = true
        error = e
      end
      if has_error
        flash[:alert] = "#{error}"
        render :new
      else
        redirect_to admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), notice: t("notices.messages.shop_product.successfully_created")
      end
    else
      redirect_to new_admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), alert: t("notices.messages.shop_product.can_not_create_shop_product")
    end

    # respond_to do |format|
    #   if @shop_product.save
    #     format.html { redirect_to admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), notice: 'Shop product was successfully created.' }
    #     format.json { render :show, status: :created, location: @shop_product }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @shop_product.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /shop_products/1
  # PATCH/PUT /shop_products/1.json
  def update
    respond_to do |format|
      if @shop_product.update(shop_product_params)
        format.html { redirect_to admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, uid:@shop_product.uid), notice: 'Shop product was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_product }
      else
        format.html { render :edit }
        format.json { render json: @shop_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_products/1
  # DELETE /shop_products/1.json
  def destroy
    @shop_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), notice: 'Shop product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = @main_business_client.shops.find_by_uid(params[:shop_uid])
      raise "NotFoud" if @shop.nil?
    end

    def set_shop_product
      @shop_product = @shop.shop_products.find_by_uid(params[:uid])
      raise "NotFoud" if @shop.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_product_params
      p = params.require(:shop_product).permit(:price, :quantity)
      p[:shop_id] = @shop.id
      p
    end
end

product_management/app/helpers/shop_products_helper.rb
module ShopProductsHelper
end

product_management/app/views/admin/shop_products/_form.html.erb
<%= form_tag(admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), method: :post, html: {class: "form-horizontal"})%>
<%= render 'layouts/errors', objects: [@shop_product] %>
  <div class="for-body">
    <div class="row">
      <div class="form-group">
        <%= label_tag :product, t("helpers.label.shop_product.product"), class: "col-md-3 control-label text-right required_asterisk" %>
        <div class="col-md-9">
          <% if @products.count > 0 %>
            <% @products.each do |product| %>
              <label><%= check_box_tag "product_ids[]", product.id, (), class:"product_check_box" %><%= product.name %></label><br>
            <% end %>
          <% else %>
            <p><%= t("pages.shop_product.no_select_product") %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <div class="rows">
      <div class="col-md-offset-3 col-md-9">
        <%= link_to t("button.back"), admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), class: "btn blue-hoki" %>
        <%= submit_tag "Save", class: "btn green-haze"%>
      </div>
    </div>
  </div>

product_management/app/views/admin/shop_products/_form_edit.html.erb
<%= form_for(@shop_product,url: admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, uid: @shop_product.uid), method: :patch, html:{class: "form-horizontal"}) do |f| %>
<%= render 'layouts/errors', objects: [@shop_product] %>
  <div class="form-body">
    <div class="form-group">
      <%= f.label :price, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.number_field :price, class: "form-control", placeholder: "input shop price" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :quantity, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.number_field :quantity, class: "form-control", placeholder: "input quantity number" %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <div class="rows">
      <div class="col-md-offset-3 col-md-9">
        <%= link_to t("button.back"), admin_shops_path(business_client_key: @main_business_client.key), class: "btn blue-hoki" %>
        <%= f.submit "Save", class: "btn green-haze"%>
      </div>
    </div>
  </div>

<% end %>

product_management/app/views/admin/shop_products/_shop_product_add_ons.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Shop Product Add On </span>
    </div>
    <div class="actions">
      <%= link_to new_admin_shop_shop_product_shop_product_add_on_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, shop_product_uid: shop_product.uid), class: "btn blue" do %>
        <i class="fa fa-plus"></i>
        <%= t("button.new") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table should-datatable table-condensed">
        <thead>
          <tr>
            <th> Delete </th>
            <th><%= t("helpers.label.shop_product_add_on.name") %></th>
            <th><%= t("helpers.label.shop_product_add_on.price") %></th>
          </tr>
        </thead>

        <tbody>
          <% shop_product.shop_product_add_ons.each do |shop_product_add_on| %>
            <tr>
              <td> <%= delete_button(admin_shop_shop_product_shop_product_add_on_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, shop_product_uid: shop_product.uid, uid: shop_product_add_on.uid)) %></td>
              <td class="ax-one-line"><%= shop_product_add_on.name %></td>
              <td class="ax-one-line"><%= shop_product_add_on.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

product_management/app/views/admin/shop_products/edit.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Edit Shop Product </span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form_edit' %>
    </div>
  </div>
</div>

product_management/app/views/admin/shop_products/index.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Shop Product </span>
    </div>
    <div class="actions">
      <%= link_to new_admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid), class: "btn blue" do %>
        <i class="fa fa-plus"></i>
        <%= t("button.add_product_to_shop") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table should-datatable table-condensed">
        <thead>
          <tr>
            <th>Delete</th>
            <th>Edit</th>
            <th><%= t("helpers.label.shop_product.name") %></th>
            <th><%= t("helpers.label.shop_product.price") %></th>
            <th><%= t("helpers.label.shop_product.quantity") %></th>
          </tr>
        </thead>

        <tbody>
          <% @shop_products.each do |shop_product| %>
            <tr>
              <td><%= delete_button(admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, uid: shop_product.uid)) %></td>
              <td><%= edit_button(edit_admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, uid: shop_product.uid)) %></td>
              <td class="ax-one-line"><u><%= link_to shop_product.product.name, admin_shop_shop_product_path(business_client_key: @main_business_client.key, shop_uid: @shop.uid, uid: shop_product.uid) %></u></td>
              <td class="ax-one-line"><%= shop_product.price %></td>
              <td class="ax-one-line"><%= shop_product.quantity %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>


<%= content_for :sub_sidebar do %>
  <%= render 'admin/shops/shop_sidebar', shop: @shop %>
<% end %>

product_management/app/views/admin/shop_products/new.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> New Shop Product </span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form' %>
    </div>
  </div>
</div>

product_management/app/views/admin/shop_products/show.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="fa fa-building font-green-sharp"></i>
      <span class="caption-subject bold uppercase"><%= @shop_product.product.name %></span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table ax-border">
          <tbody>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.shop.name") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @shop_product.product.name %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.shop.price") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @shop_product.price %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.shop.quantity") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @shop_product.quantity %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render 'shop_product_add_ons', shop_product: @shop_product %>

<%= content_for :sub_sidebar do %>
  <%= render 'admin/shops/shop_sidebar', shop: @shop %>
<% end %>