product_management/config/routes.rb
Rails.application.routes.draw do

  # devise_for :employees
  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords:'admins/passwords', confirmations:'admins/confirmations', unlocks:'admins/unlocks'}

  scope "(:locale)" do
    root to: "admin/admins#index"
    namespace :admin, path: "admin/:business_client_key" do
      root to: "admins#index"
      resources :admins, param: :uid
      resources :product_groups, param: :uid do
        resources :products, param: :uid do
          resources :product_add_ons, param: :uid
        end
      end
      resources :shops, param: :uid do
        resources :shop_operation_times, param: :uid
        resources :time_interval_products, param: :uid
        resources :employees, param: :uid
        resources :statuses, param: :uid
        resources :shop_products, param: :uid do
          resources :shop_product_add_ons, param: :uid
        end
      end

      resources :order_product_add_ons, param: :uid
      resources :order_products, param: :uid
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end
      resources :add_ons, param: :uid
      resources :business_clients, param: :uid
    end

    namespace :customer, path: "customer/:business_client_key" do
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end

    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

product_management/app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id                 :integer          not null, primary key
#  uid                :text
#  name               :text
#  business_client_id :integer
#  address            :text
#  telephone          :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Shop < ApplicationRecord
  belongs_to :business_client

  has_many :employees
  has_many :orders
  has_many :shop_operation_times
  has_many :shop_products
  has_many :statuses
  has_many :time_interval_products

  validates :name, presence: true
  validates :address, presence: true
  validates :telephone, presence: true, format: { with: /\A[0-9()#-]*\z/ }
  validates :business_client, presence: true

end

product_management/app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::AppController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = @main_business_client.shops
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.business_client = @main_business_client
    respond_to do |format|
      if @shop.save
        format.html { redirect_to admin_shops_path(business_client_key: @main_business_client.key), notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to admin_shop_path(business_client_key: @main_business_client.key,uid: @shop.uid), notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = @main_business_client.shops.find_by_uid(params[:uid])
      raise "NotFoud" if @shop.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :address, :telephone)
    end
end

product_management/app/helpers/shops_helper.rb
module ShopsHelper
end

product_management/app/views/admin/shops/_form.html.erb
<%= form_for(@shop,url: @shop.new_record? ? admin_shops_path(business_client_key: @main_business_client.key) : admin_shop_path(business_client_key: @main_business_client.key, uid: @shop.uid), method: @shop.new_record? ? "POST" : "PATCH", html:{class: "form-horizontal"}) do |f| %>
<%= render 'layouts/errors', objects: [@shop] %>
  <div class="form-body">
    <div class="form-group">
      <%= f.label :name, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :name, class: "form-control", placeholder: "input shop address" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :address, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.text_area :address, class: "form-control", placeholder: "input shop address" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :telephone, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :telephone, class: "form-control", placeholder: "input telephone number" %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <div class="rows">
      <div class="col-md-offset-3 col-md-9">
        <%= link_to t("button.back"), admin_shops_path(business_client_key: @main_business_client.key), class: "btn blue-hoki" %>
        <%= f.submit "Save", class: "btn green-haze"%>
      </div>
    </div>
  </div>

<% end %>

product_management/app/views/admin/shops/_shop_sidebar.html.erb
<div class="portlet light portlet-fit bordered setting_sidebar">
  <div class="bold portlet-title uppercase header-setting-sidebar first-setting-header"><%= shop.name %></div>
  <div class="margin-top-10 profile-usermenu">
    <ul class="nav">
      <li class="">
        <a class="nav-link" href="<%= admin_shop_path(business_client_key: @main_business_client.key,  uid: shop.uid) %>">
          <i class="fa fa-info"></i>
          <span class="title"><%= t("pages.shop.info") %></span>
        </a>
      </li>
      <li class="">
        <a class="nav-link" href="<%= admin_shop_shop_operation_times_path(business_client_key: @main_business_client.key, shop_uid: shop.uid) %>">
          <i class="fa fa-user"></i>
          <span class="title"><%= t("pages.shop.shop_operation_times") %></span>
        </a>
      </li>
      <li class="">
        <a class="nav-link" href="<%= admin_shop_employees_path(business_client_key: @main_business_client.key, shop_uid: shop.uid) %>">
          <i class="fa fa-user"></i>
          <span class="title"><%= t("pages.shop.employees") %></span>
        </a>
      </li>
      <li class="">
        <a class="nav-link" href="<%= admin_shop_statuses_path(business_client_key: @main_business_client.key, shop_uid: shop.uid) %>">
          <i class="fa fa-user"></i>
          <span class="title"><%= t("pages.shop.status") %></span>
        </a>
      </li>
      <li class="">
        <a class="nav-link" href="<%= admin_shop_time_interval_products_path(business_client_key: @main_business_client.key, shop_uid: shop.uid) %>">
          <i class="fa fa-user"></i>
          <span class="title"><%= t("pages.shop.time_interval_product") %></span>
        </a>
      </li>
      <li class="">
        <a class="nav-link" href="<%= admin_shop_shop_products_path(business_client_key: @main_business_client.key, shop_uid: shop.uid) %>">
          <i class="fa fa-user"></i>
          <span class="title"><%= t("pages.shop.shop_product") %></span>
        </a>
      </li>
    </ul>
  </div>
</div>

product_management/app/views/admin/shops/edit.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Edit Shop</span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form' %>
    </div>
  </div>
</div>

product_management/app/views/admin/shops/index.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="font-green-sharp"></i>
      <span class="caption-subject bold uppercase"><%= t("pages.shop.listing_shops") %></span>
    </div>
    <div class="actions">
      <%= link_to new_admin_shop_path(business_client_key: @main_business_client.key), class: "btn blue" do %>
        <i class="fa fa-plus"></i>
        <%= t("button.new") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table should-datatable table-condensed">
        <thead>
          <tr>
            <th><%= t("helpers.label.shop.name") %></th>
            <th><%= t("helpers.label.shop.telephone") %></th>
            <th><%= t("helpers.label.shop.address") %></th>
          </tr>
        </thead>

        <tbody>
          <% @shops.each do |shop| %>
            <tr>
              <td class="ax-one-line"><u><%= link_to shop.name, admin_shop_path(business_client_key: @main_business_client.key, uid: shop.uid) %></u></td>
              <td class="ax-one-line"><%= shop.telephone %></td>
              <td class="ax-one-line"><%= shop.address %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

product_management/app/views/admin/shops/new.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> New Shop </span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form' %>
    </div>
  </div>
</div>

product_management/app/views/admin/shops/show.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="fa fa-building font-green-sharp"></i>
      <span class="caption-subject bold uppercase"><%= @shop.name %></span>
    </div>
    <div class="actions pull-right">
      <%= link_to edit_admin_shop_path(business_client_key: @main_business_client.key, uid: @shop.uid), class: "btn yellow" do %>
        <i class="fa fa-edit"></i>
        <%= t("button.edit") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table ax-border">
          <tbody>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.shop.telephone") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @shop.telephone %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.shop.address") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @shop.address %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= content_for :sub_sidebar do %>
  <%= render 'admin/shops/shop_sidebar', shop: @shop %>
<% end %>