product_management/config/routes.rb
Rails.application.routes.draw do

  # devise_for :employees
  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords:'admins/passwords', confirmations:'admins/confirmations', unlocks:'admins/unlocks'}

  scope "(:locale)" do
    root to: "admin/admins#index"
    namespace :admin, path: "admin/:business_client_key" do
      root to: "admins#index"
      resources :admins, param: :uid
      resources :product_groups, param: :uid do
        resources :products, param: :uid do
          resources :product_add_ons, param: :uid
        end
      end
      resources :shops, param: :uid do
        resources :shop_operation_times, param: :uid
        resources :time_interval_products, param: :uid
        resources :employees, param: :uid
        resources :statuses, param: :uid
        resources :shop_products, param: :uid do
          resources :shop_product_add_ons, param: :uid
        end
      end

      resources :order_product_add_ons, param: :uid
      resources :order_products, param: :uid
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end
      resources :add_ons, param: :uid
      resources :business_clients, param: :uid
    end

    namespace :customer, path: "customer/:business_client_key" do
      resources :customers, param: :uid do
        resources :orders, param: :uid
      end

    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

product_management/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer          not null, primary key
#  uid                :text
#  name               :text
#  price              :decimal(, )
#  quantity           :integer
#  business_client_id :integer
#  product_group_id   :integer
#  tag_criteria       :jsonb
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :business_client
  belongs_to :product_group

  has_many :product_add_ons
  has_many :shop_products

  validates :name , presence: true
  validates :business_client , presence: true

end

product_management/app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AppController
  before_action :set_product_group
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @product_group.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.product_group = @product_group
    @product.business_client = @main_business_client
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_group_products_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_group_product_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid, uid: @product.uid), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_group
      @product_group = @main_business_client.product_groups.find_by_uid(params[:product_group_uid])
      raise "NotFoud" if @product_group.nil?
    end

    def set_product
      @product = @product_group.products.find_by_uid(params[:uid])
      raise "NotFoud" if @product.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      p = params.require(:product).permit(:name, :price, :quantity)
      p[:tag_criteria] = params[:product][:tag_criteria]
      p
    end

end

product_management/app/helpers/products_helper.rb
module ProductsHelper
end

product_management/app/views/admin/products/_form.html.erb
<%= form_for(@product, url: @product.new_record? ? admin_product_group_products_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid) : admin_product_group_product_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid, uid: @product.uid), method: @product.new_record? ? "POST" : "PATCH", html:{class: "form-horizontal"} ) do |f| %>
<%= render 'layouts/errors', objects: [@product] %>

  <div class="form-body">
    <div class="form-group">
      <%= f.label :name, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :name, class: "form-control", placeholder: "input produtct name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.number_field :price, class: "form-control", placeholder: "input produtct price" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :quantity, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.number_field :quantity, class: "form-control", placeholder: "input produtct quantity" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :tag_criteria, class: "col-md-3 control-label" %>
      <div class="col-md-9">
        <%= f.select :tag_criteria, options_for_select([],@product.tag_criteria), {}, class: "form-control", multiple: true, style:"width: 100%" %>
        <%= f.label :tag_criteria_help, class: "help-block" %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <div class="rows">
      <div class="col-md-offset-3 col-md-9">
        <%= link_to t("button.back"), admin_product_group_products_path(business_client_key: @main_business_client.key), class: "btn blue-hoki" %>
        <%= f.submit "Save", class: "btn green-haze" %>
      </div>
    </div>
  </div>
<% end %>

<%= content_for :jsb do %>
  <script>
    $('#product_tag_criteria').select2({
      tags: true
    })
  </script>
<% end %>

product_management/app/views/admin/products/_product_add_ons.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Product Add On </span>
    </div>
    <div class="actions">
      <%= link_to new_admin_product_group_product_product_add_on_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid, product_uid: product.uid), class: "btn blue" do %>
        <i class="fa fa-plus"></i>
        <%= t("button.new") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table should-datatable table-condensed">
        <thead>
          <tr>
            <th> Delete </th>
            <th> Update </th>
            <th><%= t("helpers.label.product_add_on.name") %></th>
            <th><%= t("helpers.label.product_add_on.price") %></th>
          </tr>
        </thead>

        <tbody>
          <% product.product_add_ons.each do |product_add_on| %>
            <tr>
              <td> <%= delete_button(admin_product_group_product_product_add_on_path(business_client_key: @main_business_client.key, product_group_uid: product.product_group.uid, product_uid: product.uid, uid: product_add_on.uid)) %></td>
              <td> <%= edit_button(edit_admin_product_group_product_product_add_on_path(business_client_key: @main_business_client.key, product_group_uid: product.product_group.uid, product_uid: product.uid, uid: product_add_on.uid)) %> </td>
              <td class="ax-one-line"><%= product_add_on.add_on.name %></td>
              <td class="ax-one-line"><%= product_add_on.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

product_management/app/views/admin/products/edit.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Edit Product </span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form' %>
    </div>
  </div>
</div>

product_management/app/views/admin/products/index.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> Product </span>
    </div>
    <div class="actions">
      <%= link_to new_admin_product_group_product_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid), class: "btn blue" do %>
        <i class="fa fa-plus"></i>
        <%= t("button.new") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table should-datatable table-condensed">
        <thead>
          <tr>
            <th><%= t("helpers.label.product.name") %></th>
            <th><%= t("helpers.label.product.price") %></th>
            <th><%= t("helpers.label.product.quantity") %></th>
            <th><%= t("helpers.label.product.tag_criteria") %></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td class="ax-one-line"><u><%= link_to product.name, admin_product_group_product_path(business_client_key: @main_business_client.key,product_group_uid: @product_group.uid, uid: product.uid) %></u></td>
              <td class="ax-one-line"><%= product.price %></td>
              <td class="ax-one-line"><%= product.quantity %></td>
              <td class="ax-one-line"><%= product.tag_criteria %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= content_for :sub_sidebar do %>
  <%= render 'admin/product_groups/product_group_sidebar', product_group: @product_group %>
<% end %>

product_management/app/views/admin/products/new.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="icon-settings font-green-sharp"></i>
      <span class="caption-subject bold uppercase"> New Product </span>
    </div>
  </div>
  <div class="portlet-body">
    <div class="form">
      <%= render 'form' %>
    </div>
  </div>
</div>

product_management/app/views/admin/products/show.html.erb
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-green-sharp">
      <i class="fa fa-building font-green-sharp"></i>
      <span class="caption-subject bold uppercase"><%= @product.name %></span>
    </div>
    <div class="actions pull-right">
      <%= link_to edit_admin_product_group_product_path(business_client_key: @main_business_client.key, product_group_uid: @product_group.uid, uid: @product.uid), class: "btn yellow" do %>
        <i class="fa fa-edit"></i>
        <%= t("button.edit") %>
      <% end %>
    </div>
  </div>
  <div class="portlet-body">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table ax-border">
          <tbody>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.product.name") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @product.name %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.product.price") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @product.price %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.product.quantity") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @product.quantity %></td>
            </tr>
            <tr>
              <td class="ax-title-width-table"><strong><%= t("helpers.label.product.tag_criteria") %>:</strong></td>
              <td class="ax-text-value-blank"><%= @product.tag_criteria %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render 'product_add_ons', product: @product %>

<%= content_for :sub_sidebar do %>
  <%= render 'admin/product_groups/product_group_sidebar', product_group: @product_group %>
<% end %>